"use strict";
"use client";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.dynamic = void 0;
exports.default = AdminLoginPage;
const jsx_runtime_1 = require("react/jsx-runtime");
exports.dynamic = "force-dynamic";
const react_1 = require("react");
const CredentialLoginForm_1 = __importDefault(require("@/components/CredentialLoginForm"));
function AdminLoginPage() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "relative min-h-screen overflow-hidden bg-[#0b0e13] text-slate-100", children: [(0, jsx_runtime_1.jsxs)("div", { className: "pointer-events-none absolute inset-0", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute -top-32 left-1/2 h-80 w-[38rem] -translate-x-1/2 rounded-full bg-gradient-to-br from-yellow-400/20 via-amber-300/10 to-fuchsia-500/10 blur-3xl" }), (0, jsx_runtime_1.jsx)("div", { className: "absolute bottom-[-10rem] right-[-8rem] h-96 w-[40rem] rounded-full bg-gradient-to-tr from-purple-700/20 to-blue-600/20 blur-3xl" })] }), (0, jsx_runtime_1.jsx)("main", { className: "relative mx-auto flex min-h-screen max-w-5xl items-center justify-center px-6", children: (0, jsx_runtime_1.jsxs)("div", { className: "grid w-full gap-10 md:grid-cols-2", children: [(0, jsx_runtime_1.jsxs)("section", { className: "flex flex-col items-start justify-center space-y-3", children: [(0, jsx_runtime_1.jsxs)("div", { className: "inline-flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "h-10 w-10 rounded-2xl bg-gradient-to-br from-yellow-400 to-orange-500 shadow-[0_8px_30px_rgba(0,0,0,.3)]" }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("div", { className: "text-lg font-semibold", children: "BetechOps" }), (0, jsx_runtime_1.jsx)("div", { className: "text-xs text-slate-400", children: "Operations Control Center" })] })] }), (0, jsx_runtime_1.jsx)("h1", { className: "text-3xl font-semibold leading-tight md:text-4xl", children: "Admin Login" }), (0, jsx_runtime_1.jsx)("p", { className: "max-w-md text-slate-400", children: "Sign in with your company email and password to manage shops, attendants, and reports." })] }), (0, jsx_runtime_1.jsx)("section", { className: "flex items-center justify-center", children: (0, jsx_runtime_1.jsxs)("div", { className: "w-full max-w-md rounded-2xl border border-white/10 bg-[linear-gradient(135deg,rgba(18,22,32,.9),rgba(18,22,32,.7))] p-6 shadow-[0_10px_30px_rgba(0,0,0,.35)] backdrop-blur", children: [(0, jsx_runtime_1.jsx)(react_1.Suspense, { fallback: (0, jsx_runtime_1.jsx)("div", { className: "py-6", children: "Loading\u2026" }), children: (0, jsx_runtime_1.jsx)(CredentialLoginForm_1.default, { defaultRedirect: "/auth/post-login?intended=admin", title: "Admin sign in", description: "Admins use your betech.co.ke email and password." }) }), (0, jsx_runtime_1.jsx)("div", { className: "mt-6 h-px w-full bg-gradient-to-r from-transparent via-white/10 to-transparent" }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-4 text-xs text-slate-400", children: ["Need help? Email", " ", (0, jsx_runtime_1.jsx)("a", { href: "mailto:kiokojackson81@gmail.com", className: "underline underline-offset-2 text-slate-300 hover:text-white", children: "support" }), "."] })] }) })] }) })] }));
}
