export const COMPLAINT_STATUSES = ["NEW", "UNDER_REVIEW", "CUSTOMER_CONTACTED", "WAITING_FOR_CUSTOMER", "TECHNICAL_REVIEW", "SITE_VISIT_REQUIRED", "WARRANTY_REVIEW", "RESOLVED", "CLOSED"] as const;
export const COMPLAINT_PRIORITIES = ["LOW", "NORMAL", "HIGH", "URGENT"] as const;
