"use strict";
"use client";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.dynamic = void 0;
exports.default = AttendantLoginPage;
const jsx_runtime_1 = require("react/jsx-runtime");
exports.dynamic = "force-dynamic";
const react_1 = require("react");
const link_1 = __importDefault(require("next/link"));
const CredentialLoginForm_1 = __importDefault(require("@/components/CredentialLoginForm"));
function AttendantLoginPage() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "relative min-h-screen overflow-hidden bg-[#0b0e13] text-slate-100", children: [(0, jsx_runtime_1.jsxs)("div", { className: "pointer-events-none absolute inset-0", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute -top-28 left-1/2 h-72 w-[30rem] -translate-x-1/2 rounded-full bg-gradient-to-br from-sky-400/25 via-cyan-300/10 to-fuchsia-500/10 blur-3xl" }), (0, jsx_runtime_1.jsx)("div", { className: "absolute bottom-[-10rem] left-[-8rem] h-96 w-[36rem] rounded-full bg-gradient-to-tr from-indigo-600/20 to-blue-500/20 blur-3xl" })] }), (0, jsx_runtime_1.jsx)("main", { className: "relative mx-auto flex min-h-screen max-w-5xl items-center justify-center px-6", children: (0, jsx_runtime_1.jsxs)("div", { className: "grid w-full gap-8 md:grid-cols-2", children: [(0, jsx_runtime_1.jsxs)("section", { className: "flex flex-col items-start justify-center", children: [(0, jsx_runtime_1.jsxs)("div", { className: "mb-6 inline-flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "h-10 w-10 rounded-2xl bg-gradient-to-br from-sky-400 to-blue-600 shadow-[0_8px_30px_rgba(0,0,0,.3)]" }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("div", { className: "text-lg font-semibold", children: "BetechOps" }), (0, jsx_runtime_1.jsx)("div", { className: "text-xs text-slate-400", children: "Attendant Portal" })] })] }), (0, jsx_runtime_1.jsx)("h1", { className: "mb-3 text-3xl font-semibold leading-tight md:text-4xl", children: "Attendant Login" }), (0, jsx_runtime_1.jsx)("p", { className: "max-w-md text-slate-400", children: "Sign in with your company email and password to manage your daily tasks." }), (0, jsx_runtime_1.jsx)("div", { className: "mt-6 text-xs text-slate-500 md:mt-10", children: (0, jsx_runtime_1.jsx)(link_1.default, { href: "/", className: "underline underline-offset-2 text-slate-300 hover:text-white", children: "Back to Home" }) })] }), (0, jsx_runtime_1.jsx)("section", { className: "flex items-center justify-center", children: (0, jsx_runtime_1.jsxs)("div", { className: "w-full max-w-md rounded-2xl border border-white/10 bg-[linear-gradient(135deg,rgba(18,22,32,.9),rgba(18,22,32,.7))] p-6 shadow-[0_10px_30px_rgba(0,0,0,.35)] backdrop-blur", children: [(0, jsx_runtime_1.jsx)(react_1.Suspense, { fallback: (0, jsx_runtime_1.jsx)("div", { className: "py-6", children: "Loading\u2026" }), children: (0, jsx_runtime_1.jsx)(CredentialLoginForm_1.default, { defaultRedirect: "/auth/post-login", title: "Credential login", description: "Use your @betech.co.ke email and password." }) }), (0, jsx_runtime_1.jsx)("div", { className: "mt-4 text-center text-xs text-slate-400", children: "Need help? Contact your admin." })] }) })] }) })] }));
}
