ALTER TABLE "DailyReport"
ADD COLUMN IF NOT EXISTS "newProducts" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "productsEdited" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "copiesUploaded" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "walkInServed" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "purchasesMade" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "liveSessionsCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "commissionEarned" DECIMAL(12,2),
ADD COLUMN IF NOT EXISTS "confirmedCompetitiveness" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "marketEngagement" JSONB,
ADD COLUMN IF NOT EXISTS "concerns" TEXT;
