"use strict";
"use client";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = ReceiptsSummary;
const jsx_runtime_1 = require("react/jsx-runtime");
function ReceiptsSummary({ summary, loading, quickRange, onApplyQuickRange, rangeLabel, }) {
    const formatCurrency = (value) => `KES ${Number(value ?? 0).toLocaleString("en-KE", { maximumFractionDigits: 0 })}`;
    const salesLabel = loading ? "Loading..." : formatCurrency(summary?.totalSales ?? 0);
    const profitLabel = loading ? "Loading..." : formatCurrency(summary?.totalProfit ?? 0);
    const profitNote = loading
        ? ""
        : summary?.hasCompleteCosts
            ? "All priced receipts"
            : (summary?.awaitingPricingCount ? `${summary.awaitingPricingCount} awaiting pricing` : "Based on priced receipts only");
    const receiptsLabel = loading ? "Loading..." : String(summary?.receiptsCount ?? 0);
    const itemsLabel = loading ? "Loading..." : String(summary?.itemsCount ?? 0);
    return ((0, jsx_runtime_1.jsxs)("section", { className: "rounded-2xl border border-white/15 bg-slate-900/70 p-4 shadow-inner shadow-black/30", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "text-xs uppercase tracking-[0.2em] text-slate-400", children: "Snapshot" }), (0, jsx_runtime_1.jsx)("h2", { className: "text-lg font-semibold text-white", children: "Receipt totals" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-slate-400", children: "Quick filters let you lock the view to today, this week, or this trading period while the list remains read-only." })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-wrap gap-2 text-[11px] font-semibold uppercase tracking-wide", children: [(0, jsx_runtime_1.jsx)("button", { type: "button", onClick: () => onApplyQuickRange("today"), className: `rounded-full border px-3 py-1 transition ${quickRange === "today"
                                    ? "border-emerald-500 bg-emerald-500/20 text-emerald-200"
                                    : "border-white/15 text-slate-200 hover:border-emerald-500 hover:text-white"}`, children: "Today" }), (0, jsx_runtime_1.jsx)("button", { type: "button", onClick: () => onApplyQuickRange("yesterday"), className: `rounded-full border px-3 py-1 transition ${quickRange === "yesterday"
                                    ? "border-emerald-500 bg-emerald-500/20 text-emerald-200"
                                    : "border-white/15 text-slate-200 hover:border-emerald-500 hover:text-white"}`, children: "Yesterday" }), (0, jsx_runtime_1.jsx)("button", { type: "button", onClick: () => onApplyQuickRange("this-week"), className: `rounded-full border px-3 py-1 transition ${quickRange === "this-week"
                                    ? "border-emerald-500 bg-emerald-500/20 text-emerald-200"
                                    : "border-white/15 text-slate-200 hover:border-emerald-500 hover:text-white"}`, children: "This week" }), (0, jsx_runtime_1.jsx)("button", { type: "button", onClick: () => onApplyQuickRange("trading-period"), className: `rounded-full border px-3 py-1 transition ${quickRange === "trading-period"
                                    ? "border-emerald-500 bg-emerald-500/20 text-emerald-200"
                                    : "border-white/15 text-slate-200 hover:border-emerald-500 hover:text-white"}`, children: "This period" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-4 grid gap-3 sm:grid-cols-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "rounded-xl border border-white/5 bg-slate-950/40 px-3 py-2", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-[11px] uppercase tracking-wide text-slate-400", children: "Total sales" }), (0, jsx_runtime_1.jsx)("p", { className: "text-xl font-semibold text-emerald-300", children: salesLabel })] }), (0, jsx_runtime_1.jsxs)("div", { className: "rounded-xl border border-white/5 bg-slate-950/40 px-3 py-2", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-[11px] uppercase tracking-wide text-slate-400", children: "Total profit" }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: `text-xl font-semibold ${summary?.hasCompleteCosts ? "text-emerald-300" : "text-slate-400"}`, children: profitLabel }), profitNote && ((0, jsx_runtime_1.jsx)("p", { className: "text-[11px] text-slate-400", children: profitNote }))] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "rounded-xl border border-white/5 bg-slate-950/40 px-3 py-2", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-[11px] uppercase tracking-wide text-slate-400", children: "Receipts" }), (0, jsx_runtime_1.jsx)("p", { className: "text-xl font-semibold text-white", children: receiptsLabel })] }), (0, jsx_runtime_1.jsxs)("div", { className: "rounded-xl border border-white/5 bg-slate-950/40 px-3 py-2", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-[11px] uppercase tracking-wide text-slate-400", children: "Products sold" }), (0, jsx_runtime_1.jsx)("p", { className: "text-xl font-semibold text-white", children: itemsLabel })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-3 text-xs text-slate-400", children: ["Range: ", (0, jsx_runtime_1.jsx)("span", { className: "font-semibold text-white", children: rangeLabel })] })] }));
}
