"use strict";
"use client";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = RowActions;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
function RowActions({ onEdit, onEditItems, onDelete, onDownload, onSendWhatsapp, onPrint, onPodAction, podActionLabel = "Mark delivered", podActionProcessing = false, disabled, }) {
    // Responsive layout: show icon + label on md+, icons-only on small screens
    const btnBase = "inline-flex items-center gap-2 rounded px-2 py-1 text-xs outline-none focus:ring-2 focus:ring-emerald-400";
    return ((0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-end gap-2", children: [(0, jsx_runtime_1.jsxs)("button", { "aria-label": "Edit receipt", title: "Edit receipt", onClick: onEdit, disabled: disabled, className: `${btnBase} bg-slate-800 hover:bg-slate-700 text-slate-100`, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Edit3, { size: 16 }), (0, jsx_runtime_1.jsx)("span", { className: "hidden md:inline", children: "Edit" })] }), (0, jsx_runtime_1.jsxs)("button", { "aria-label": "Edit items", title: "Edit items", onClick: onEditItems, disabled: disabled, className: `${btnBase} bg-slate-800 hover:bg-slate-700 text-slate-100`, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Edit3, { size: 16 }), (0, jsx_runtime_1.jsx)("span", { className: "hidden md:inline", children: "Items" })] }), (0, jsx_runtime_1.jsxs)("button", { "aria-label": "Delete receipt", title: "Delete", onClick: onDelete, disabled: disabled, className: `${btnBase} bg-rose-700 hover:bg-rose-600 text-white`, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Trash2, { size: 16 }), (0, jsx_runtime_1.jsx)("span", { className: "hidden md:inline", children: "Delete" })] }), (0, jsx_runtime_1.jsxs)("button", { "aria-label": "Download receipt", title: "Download", onClick: onDownload, disabled: disabled, className: `${btnBase} bg-slate-700 hover:bg-slate-600 text-slate-100`, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Download, { size: 16 }), (0, jsx_runtime_1.jsx)("span", { className: "hidden md:inline", children: "Download" })] }), (0, jsx_runtime_1.jsxs)("button", { "aria-label": "Send via WhatsApp", title: "WhatsApp", onClick: onSendWhatsapp, disabled: disabled, className: `${btnBase} bg-emerald-600 hover:bg-emerald-500 text-black`, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Send, { size: 16 }), (0, jsx_runtime_1.jsx)("span", { className: "hidden md:inline", children: "WhatsApp" })] }), onPodAction && ((0, jsx_runtime_1.jsxs)("button", { "aria-label": podActionLabel, title: podActionLabel, onClick: onPodAction, disabled: disabled || podActionProcessing, className: `${btnBase} bg-yellow-500/60 hover:bg-yellow-500 text-black`, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Check, { size: 16 }), (0, jsx_runtime_1.jsx)("span", { className: "hidden md:inline", children: podActionProcessing ? "Processing..." : podActionLabel })] })), (0, jsx_runtime_1.jsxs)("button", { "aria-label": "Print receipt", title: "Print", onClick: onPrint, disabled: disabled, className: `${btnBase} bg-slate-800 hover:bg-slate-700 text-slate-100`, children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Printer, { size: 16 }), (0, jsx_runtime_1.jsx)("span", { className: "hidden md:inline", children: "Print" })] })] }));
}
