ALTER TABLE "Product"
  ADD COLUMN IF NOT EXISTS "productType" TEXT,
  ADD COLUMN IF NOT EXISTS "posEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "catalogueConfiguration" JSONB;

CREATE TABLE IF NOT EXISTS "ProductCatalogueSettings" (
  "id" TEXT NOT NULL DEFAULT 'default',
  "installationBand1Max" DOUBLE PRECISION NOT NULL DEFAULT 50000,
  "installationBand1Fee" DOUBLE PRECISION NOT NULL DEFAULT 8000,
  "installationBand2Max" DOUBLE PRECISION NOT NULL DEFAULT 100000,
  "installationBand2Fee" DOUBLE PRECISION NOT NULL DEFAULT 15000,
  "installationBand3Max" DOUBLE PRECISION NOT NULL DEFAULT 350000,
  "installationBand3Fee" DOUBLE PRECISION NOT NULL DEFAULT 25000,
  "installationBand4Max" DOUBLE PRECISION NOT NULL DEFAULT 800000,
  "installationBand4Fee" DOUBLE PRECISION NOT NULL DEFAULT 35000,
  "zone1TransportFee" DOUBLE PRECISION NOT NULL DEFAULT 3000,
  "zone2TransportFee" DOUBLE PRECISION NOT NULL DEFAULT 7500,
  "zone3TransportFee" DOUBLE PRECISION NOT NULL DEFAULT 15000,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProductCatalogueSettings_pkey" PRIMARY KEY ("id")
);

INSERT INTO "ProductCatalogueSettings" ("id")
VALUES ('default')
ON CONFLICT ("id") DO NOTHING;
