"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Refund = { id: string; paymentId: string; amount: number; status: string; reason: string; payer: string; createdAt: string; authorizedAt: string | null; completedAt: string | null; providerResultDesc: string | null; original: { receipt: string | null; reference: string | null; channel: string }; requestedBy: string; authorizedBy: string | null };
type Payment = { id: string; status: string; channel: string; amount: number; receipt: string | null; payer: string | null; reference: string | null; linked: { total: number; paid: number } | null; refunded: number } | null;
const money = new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 });
const time = new Intl.DateTimeFormat("en-KE", { dateStyle: "medium", timeStyle: "short" });

export default function RefundsClient({ paymentId }: { paymentId: string }) {
  const [refunds, setRefunds] = useState<Refund[]>([]);
  const [payment, setPayment] = useState<Payment>(null);
  const [amount, setAmount] = useState("");
  const [reason, setReason] = useState("");
  const [otp, setOtp] = useState("");
  const [selected, setSelected] = useState<Refund | null>(null);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    const response = await fetch(`/api/admin/mpesa-refunds${paymentId ? `?paymentId=${encodeURIComponent(paymentId)}` : ""}`, { cache: "no-store" });
    const body = await response.json();
    if (!response.ok || !body.ok) throw new Error(body.error || "Unable to load refund records");
    setRefunds(body.refunds); setPayment(body.payment); setSelected((current) => body.refunds.find((refund: Refund) => refund.id === current?.id) || current);
  }, [paymentId]);
  useEffect(() => { void load().catch((loadError) => setError(loadError.message)); }, [load]);
  const remaining = useMemo(() => payment ? Math.max(0, payment.amount - payment.refunded) : 0, [payment]);
  async function action(path: string, options?: RequestInit) {
    setBusy(true); setError(""); setNotice("");
    try { const response = await fetch(path, options); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error || "Refund action failed"); setNotice(body.message || `Refund is now ${body.status || "updated"}.`); await load(); return body; } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "Refund action failed"); } finally { setBusy(false); }
  }
  async function create(event: FormEvent) {
    event.preventDefault(); if (!payment) return;
    const body = await action("/api/admin/mpesa-refunds", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ paymentId: payment.id, amount: Number(amount), reason }) });
    if (body?.refund) { setSelected({ id: body.refund.id } as Refund); setAmount(""); setReason(""); }
  }
  return <main className="min-h-screen bg-slate-950 px-4 py-6 text-slate-100 lg:px-8"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-rose-300">Finance operations · restricted</p><h1 className="mt-1 text-3xl font-semibold">M-Pesa Refunds</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Refunds return only an original confirmed M-Pesa transaction to its recorded payer. A Safaricom result callback—not this screen—changes accounting.</p></div><Link href="/admin/mpesa-payments" className="rounded-xl border border-white/15 px-4 py-2 text-sm font-semibold hover:bg-white/10">Back to M-Pesa payments</Link></header>
    {error ? <p role="alert" className="rounded-xl border border-rose-300/30 bg-rose-300/10 p-3 text-sm text-rose-100">{error}</p> : null}{notice ? <p className="rounded-xl border border-emerald-300/30 bg-emerald-300/10 p-3 text-sm text-emerald-100">{notice}</p> : null}
    {payment ? <section className="rounded-2xl border border-amber-300/25 bg-slate-900/80 p-5"><h2 className="text-lg font-semibold">Start refund for original payment</h2><div className="mt-3 grid gap-3 text-sm sm:grid-cols-3"><div><span className="text-slate-400">Receipt</span><p className="font-mono">{payment.receipt || "Unavailable"}</p></div><div><span className="text-slate-400">Order / reference</span><p>{payment.reference || "Unlinked"}</p></div><div><span className="text-slate-400">Original payer</span><p className="font-mono">{payment.payer || "Unavailable"}</p></div><div><span className="text-slate-400">Original amount</span><p>{money.format(payment.amount)}</p></div><div><span className="text-slate-400">Already refunded</span><p>{money.format(payment.refunded)}</p></div><div><span className="text-slate-400">Available to refund</span><p className="font-semibold text-amber-100">{money.format(remaining)}</p></div></div>
      {payment.status !== "SUCCESS" || !payment.linked ? <p className="mt-4 text-sm text-amber-100">This payment is not eligible: it must be a successful M-Pesa payment linked to an order or website order.</p> : <form onSubmit={create} className="mt-5 grid gap-3 md:grid-cols-[180px_1fr_auto]"><input required min="1" max={remaining} step="1" inputMode="numeric" type="number" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Refund amount" className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm" /><input required minLength={5} maxLength={500} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason for refund (recorded in audit log)" className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm" /><button disabled={busy || remaining <= 0} className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-bold text-slate-950 disabled:opacity-50">Create protected refund</button></form>}</section> : <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5 text-sm text-slate-300">Choose a successful payment from <Link href="/admin/mpesa-payments" className="font-semibold text-amber-200 underline">M-Pesa Payments</Link> to begin a refund. No recipient or amount can be entered independently of that ledger record.</section>}
    <section className="overflow-x-auto rounded-2xl border border-white/10 bg-slate-900/70"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-400"><tr><th className="p-3">Original receipt</th><th className="p-3">Amount</th><th className="p-3">Payer</th><th className="p-3">Reason</th><th className="p-3">Status</th><th className="p-3">Requested</th><th className="p-3">Action</th></tr></thead><tbody>{refunds.map((refund) => <tr key={refund.id} className="border-b border-white/5"><td className="p-3"><p className="font-mono text-xs">{refund.original.receipt || "—"}</p><p className="text-xs text-slate-400">{refund.original.reference || "—"} · {refund.original.channel}</p></td><td className="p-3 font-semibold">{money.format(refund.amount)}</td><td className="p-3 font-mono text-xs">{refund.payer}</td><td className="max-w-[230px] p-3 text-xs">{refund.reason}</td><td className="p-3"><span className="rounded-full border border-white/15 px-2 py-1 text-xs font-semibold">{refund.status}</span><p className="mt-1 max-w-[220px] text-xs text-slate-400">{refund.providerResultDesc || ""}</p></td><td className="p-3 text-xs">{time.format(new Date(refund.createdAt))}<br />{refund.requestedBy}</td><td className="p-3"><button type="button" onClick={() => { setSelected(refund); setOtp(""); }} className="rounded-lg border border-amber-300/35 px-3 py-1.5 text-xs font-bold text-amber-100 hover:bg-amber-300/10">Review</button></td></tr>)}{!refunds.length ? <tr><td colSpan={7} className="p-8 text-center text-slate-400">No M-Pesa refund requests.</td></tr> : null}</tbody></table></section>
    {selected ? <section className="rounded-2xl border border-amber-300/30 bg-slate-900 p-5"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-semibold">Refund confirmation</h2><p className="mt-1 text-sm text-slate-300">{money.format(selected.amount)} · original receipt <span className="font-mono">{selected.original.receipt || "—"}</span> · payer <span className="font-mono">{selected.payer}</span></p></div><button onClick={() => setSelected(null)} className="text-sm text-slate-300">Close</button></div><p className="mt-4 rounded-lg border border-white/10 bg-slate-950/70 p-3 text-sm text-slate-300">The recipient and refund amount are locked to this approved ledger record. Safaricom must confirm the reversal before the order balance changes.</p>{selected.status === "DRAFT" ? <button disabled={busy} onClick={() => void action(`/api/admin/mpesa-refunds/${selected.id}/otp`, { method: "POST" })} className="mt-4 rounded-lg bg-amber-400 px-4 py-2 text-sm font-bold text-slate-950">Send my approval code</button> : null}{selected.status === "OTP_PENDING" ? <div className="mt-4 flex flex-wrap gap-2"><input value={otp} onChange={(event) => setOtp(event.target.value)} maxLength={6} inputMode="numeric" placeholder="6-digit approval code" className="rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm" /><button disabled={busy || otp.length !== 6} onClick={() => void action(`/api/admin/mpesa-refunds/${selected.id}/authorize`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code: otp }) })} className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-bold text-slate-950">Verify code</button></div> : null}{selected.status === "AUTHORIZED" ? <button disabled={busy} onClick={() => void action(`/api/admin/mpesa-refunds/${selected.id}/execute`, { method: "POST" })} className="mt-4 rounded-lg bg-rose-500 px-4 py-2 text-sm font-bold text-white">Submit to Safaricom</button> : null}{selected.status === "PROCESSING" ? <p className="mt-4 text-sm text-sky-100">Awaiting Safaricom's final reversal callback. Refresh this page to see its outcome.</p> : null}</section> : null}
  </div></main>;
}
