export const kenyaCountyMarkets = [
  { county: "Mombasa", towns: ["Mombasa", "Nyali", "Bamburi", "Likoni", "Changamwe"] },
  { county: "Kwale", towns: ["Ukunda", "Diani", "Msambweni", "Kwale", "Lunga Lunga"] },
  { county: "Kilifi", towns: ["Kilifi", "Malindi", "Mariakani", "Watamu", "Mtwapa"] },
  { county: "Tana River", towns: ["Hola", "Garsen", "Bura"] },
  { county: "Lamu", towns: ["Lamu", "Mpeketoni", "Witu"] },
  { county: "Taita Taveta", towns: ["Voi", "Taveta", "Wundanyi", "Mwatate"] },
  { county: "Garissa", towns: ["Garissa", "Dadaab", "Modogashe"] },
  { county: "Wajir", towns: ["Wajir", "Habaswein", "Eldas"] },
  { county: "Mandera", towns: ["Mandera", "Elwak", "Rhamu"] },
  { county: "Marsabit", towns: ["Marsabit", "Moyale", "Loiyangalani"] },
  { county: "Isiolo", towns: ["Isiolo", "Garbatulla", "Merti"] },
  { county: "Meru", towns: ["Meru", "Maua", "Nkubu", "Timau"] },
  { county: "Tharaka Nithi", towns: ["Chuka", "Kathwana", "Chogoria"] },
  { county: "Embu", towns: ["Embu", "Runyenjes", "Siakago"] },
  { county: "Kitui", towns: ["Kitui", "Mwingi", "Mutomo"] },
  { county: "Machakos", towns: ["Machakos", "Athi River", "Tala", "Kangundo"] },
  { county: "Makueni", towns: ["Wote", "Emali", "Makindu", "Kibwezi"] },
  { county: "Nyandarua", towns: ["Ol Kalou", "Engineer", "Njabini"] },
  { county: "Nyeri", towns: ["Nyeri", "Karatina", "Othaya", "Naro Moru"] },
  { county: "Kirinyaga", towns: ["Kerugoya", "Kutus", "Wang’uru", "Sagana"] },
  { county: "Murang’a", towns: ["Murang’a", "Kenol", "Maragwa"] },
  { county: "Kiambu", towns: ["Thika", "Ruiru", "Kiambu", "Kikuyu", "Limuru"] },
  { county: "Turkana", towns: ["Lodwar", "Kakuma", "Lokichogio"] },
  { county: "West Pokot", towns: ["Kapenguria", "Ortum"] },
  { county: "Samburu", towns: ["Maralal", "Baragoi", "Wamba"] },
  { county: "Trans Nzoia", towns: ["Kitale", "Endebess"] },
  { county: "Uasin Gishu", towns: ["Eldoret", "Turbo", "Burnt Forest"] },
  { county: "Elgeyo Marakwet", towns: ["Iten", "Kapsowar", "Tambach"] },
  { county: "Nandi", towns: ["Kapsabet", "Nandi Hills"] },
  { county: "Baringo", towns: ["Kabarnet", "Eldama Ravine", "Marigat"] },
  { county: "Laikipia", towns: ["Nanyuki", "Nyahururu", "Rumuruti"] },
  { county: "Nakuru", towns: ["Nakuru", "Naivasha", "Gilgil", "Molo"] },
  { county: "Narok", towns: ["Narok", "Kilgoris"] },
  { county: "Kajiado", towns: ["Kitengela", "Ngong", "Kajiado", "Rongai"] },
  { county: "Kericho", towns: ["Kericho", "Litein", "Londiani"] },
  { county: "Bomet", towns: ["Bomet", "Sotik", "Longisa"] },
  { county: "Kakamega", towns: ["Kakamega", "Mumias", "Malava"] },
  { county: "Vihiga", towns: ["Mbale", "Luanda", "Chavakali"] },
  { county: "Bungoma", towns: ["Bungoma", "Webuye", "Kimilili"] },
  { county: "Busia", towns: ["Busia", "Malaba", "Bumala"] },
  { county: "Siaya", towns: ["Siaya", "Bondo", "Ugunja"] },
  { county: "Kisumu", towns: ["Kisumu", "Ahero", "Muhoroni"] },
  { county: "Homa Bay", towns: ["Homa Bay", "Mbita", "Oyugis"] },
  { county: "Migori", towns: ["Migori", "Rongo", "Kehancha"] },
  { county: "Kisii", towns: ["Kisii", "Ogembo", "Keroka"] },
  { county: "Nyamira", towns: ["Nyamira", "Keroka", "Nyansiongo"] },
  { county: "Nairobi", towns: ["Nairobi CBD", "Westlands", "Eastleigh", "Kasarani", "Embakasi"] },
] as const;

export const kenyaCountyOptions = kenyaCountyMarkets.map((entry) => entry.county);

export function getTownsForCounty(county: string) {
  const match = kenyaCountyMarkets.find((entry) => entry.county === county);
  return match ? [...match.towns] : [];
}
