"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { COMPLAINT_PRIORITIES, COMPLAINT_STATUSES } from "@/lib/complaintsClientShared";

type Initial = { reference: string; status: string; priority: string; assignedToId: string | null; technicalFindings: string | null; warrantyFindings: string | null; siteVisitInfo: string | null; resolution: string | null };
export default function ComplaintManagementClient({ initial, staff }: { initial: Initial; staff: Array<{ id: string; name: string | null; email: string | null }> }) {
  const router = useRouter(); const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [message, setMessage] = useState(""); const [visibility, setVisibility] = useState<"CUSTOMER" | "INTERNAL">("CUSTOMER");
  const input = "w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-slate-100 outline-none focus:border-cyan-400/40";
  async function save() { setBusy(true); setNotice(""); const response = await fetch(`/api/admin/complaints/${encodeURIComponent(initial.reference)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); setNotice(response.ok ? "Case updated." : data.error || "Update failed."); if (response.ok) router.refresh(); setBusy(false); }
  async function send() { setBusy(true); setNotice(""); const response = await fetch(`/api/admin/complaints/${encodeURIComponent(initial.reference)}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, visibility }) }); const data = await response.json(); setNotice(response.ok ? (visibility === "INTERNAL" ? "Internal note saved." : "Customer reply saved.") : data.error || "Message failed."); if (response.ok) { setMessage(""); router.refresh(); } setBusy(false); }
  return <div className="space-y-5"><section className="rounded-[26px] border border-white/10 bg-slate-900/80 p-5"><h2 className="text-xl font-semibold">Case management</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold uppercase tracking-wider text-slate-400">Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className={`${input} mt-2 normal-case`}>{COMPLAINT_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label><label className="text-xs font-bold uppercase tracking-wider text-slate-400">Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} className={`${input} mt-2 normal-case`}>{COMPLAINT_PRIORITIES.map((priority) => <option key={priority}>{priority}</option>)}</select></label><label className="text-xs font-bold uppercase tracking-wider text-slate-400">Assigned staff<select value={form.assignedToId || ""} onChange={(e) => setForm({ ...form, assignedToId: e.target.value || null })} className={`${input} mt-2 normal-case`}><option value="">Unassigned</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.name || person.email}</option>)}</select></label></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{([['technicalFindings','Technical findings'],['warrantyFindings','Warranty findings'],['siteVisitInfo','Site visit information'],['resolution','Resolution']] as const).map(([key,label]) => <label key={key} className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}<textarea rows={4} value={form[key] || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={`${input} mt-2 normal-case`} /></label>)}</div><button type="button" disabled={busy} onClick={() => void save()} className="mt-4 rounded-2xl bg-cyan-400 px-5 py-3 font-bold text-slate-950 disabled:opacity-60">Save case update</button></section>
    <section className="rounded-[26px] border border-white/10 bg-slate-900/80 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Communication</h2><p className="mt-1 text-sm text-slate-400">Customer replies are visible in their account. Internal notes never leave the staff desk.</p></div><div className="flex rounded-xl bg-slate-950 p-1"><button onClick={() => setVisibility("CUSTOMER")} className={`rounded-lg px-3 py-2 text-xs font-bold ${visibility === "CUSTOMER" ? "bg-cyan-400 text-slate-950" : "text-slate-400"}`}>Customer reply</button><button onClick={() => setVisibility("INTERNAL")} className={`rounded-lg px-3 py-2 text-xs font-bold ${visibility === "INTERNAL" ? "bg-amber-400 text-slate-950" : "text-slate-400"}`}>Internal note</button></div></div><textarea rows={4} value={message} onChange={(e) => setMessage(e.target.value)} placeholder={visibility === "INTERNAL" ? "Add private handling notes..." : "Write an update for the customer..."} className={`${input} mt-4`} /><button type="button" disabled={busy || !message.trim()} onClick={() => void send()} className={`mt-3 rounded-2xl px-5 py-3 font-bold text-slate-950 disabled:opacity-50 ${visibility === "INTERNAL" ? "bg-amber-400" : "bg-cyan-400"}`}>{visibility === "INTERNAL" ? "Save internal note" : "Send customer update"}</button>{notice ? <p className="mt-3 text-sm font-bold text-cyan-200">{notice}</p> : null}</section></div>;
}
