import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Clock3, ExternalLink, FileText, MessageCircle, Paperclip, UserRound } from "lucide-react";
import ComplaintManagementClient from "./ComplaintManagementClient";
import { auth } from "@/lib/auth";
import { complaintStaffAccess, getStaffComplaint } from "@/lib/complaints";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
const format = (value: string) => value.replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export default async function AdminComplaintDetailPage({ params }: { params: Promise<{ reference: string }> }) {
  const session = await auth(); const user = session?.user as { role?: string; attendantCategory?: string } | undefined; if (!session) redirect("/admin/login"); if (!complaintStaffAccess(user || {})) redirect("/not-authorized");
  const complaint = await getStaffComplaint((await params).reference); if (!complaint) notFound();
  const staff = await prisma.user.findMany({ where: { isActive: true, OR: [{ role: { in: ["ADMIN", "SUPERVISOR"] } }, { attendantCategory: "SUPPORT_OPS" }] }, orderBy: { name: "asc" }, select: { id: true, name: true, email: true } });
  const customerMessages = complaint.messages.filter((message) => message.visibility === "CUSTOMER"); const notes = complaint.messages.filter((message) => message.visibility === "INTERNAL");
  return <div className="space-y-6"><section className="rounded-[30px] border border-white/10 bg-[radial-gradient(circle_at_90%_0%,rgba(34,211,238,.16),transparent_34%),linear-gradient(135deg,#111827,#020617)] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><Link href="/admin/complaints" className="text-sm font-bold text-cyan-300">← Complaint queue</Link><div className="mt-4 text-xs font-bold uppercase tracking-[.25em] text-cyan-300">{complaint.reference}</div><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{complaint.title}</h1><div className="mt-3 flex flex-wrap gap-2 text-sm text-slate-400"><span>{format(complaint.category)}</span><span>·</span><span>Opened {new Date(complaint.createdAt).toLocaleString("en-KE")}</span></div></div><div className="flex gap-2"><span className="rounded-full bg-amber-400/15 px-4 py-2 text-xs font-black uppercase tracking-wider text-amber-200">{format(complaint.status)}</span><span className="rounded-full bg-rose-400/15 px-4 py-2 text-xs font-black uppercase tracking-wider text-rose-200">{complaint.priority}</span></div></div></section>
    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-5"><section className="rounded-[26px] border border-white/10 bg-slate-900/80 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold"><UserRound className="h-5 w-5 text-cyan-300" />Customer & transaction</h2><div className="mt-4 space-y-3 text-sm"><Data label="Customer" value={complaint.customer.name || "Customer"} /><Data label="Phone" value={complaint.customer.phone || "Not provided"} /><Data label="Email" value={complaint.customer.email || "Not provided"} /><Data label="Related record" value={complaint.relatedReference || "Not linked"} /><Data label="Current system status" value={complaint.systemStatus ? format(complaint.systemStatus) : "Not provided"} /><Data label="Error code" value={complaint.errorCode || "Not provided"} /></div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/admin/customers/profile/${complaint.customer.id}`} target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-cyan-400/25 bg-cyan-400/10 px-4 py-2 text-sm font-bold text-cyan-100">Customer 360 <ExternalLink className="h-3.5 w-3.5" /></Link>{complaint.receiptId ? <Link href={`/admin/receipts?id=${complaint.receiptId}`} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold">Open receipt</Link> : null}</div></section>
      <section className="rounded-[26px] border border-white/10 bg-slate-900/80 p-5"><h2 className="text-xl font-semibold">Customer report</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-300">{complaint.description}</p></section>
      <section className="rounded-[26px] border border-white/10 bg-slate-900/80 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold"><Paperclip className="h-5 w-5 text-cyan-300" />Evidence</h2><div className="mt-4 grid gap-2">{complaint.attachments.length ? complaint.attachments.map((file) => <a key={file.id} href={file.fileUrl} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 rounded-2xl border border-white/10 bg-slate-950 p-3 text-sm"><span className="flex min-w-0 items-center gap-2"><FileText className="h-4 w-4 shrink-0 text-cyan-300" /><span className="truncate">{file.fileName}</span></span><span className="text-xs text-slate-500">{Math.ceil(file.fileSize / 1024)} KB</span></a>) : <p className="text-sm text-slate-500">No evidence attached.</p>}</div></section>
    </div><ComplaintManagementClient initial={{ reference: complaint.reference, status: complaint.status, priority: complaint.priority, assignedToId: complaint.assignedToId, technicalFindings: complaint.technicalFindings, warrantyFindings: complaint.warrantyFindings, siteVisitInfo: complaint.siteVisitInfo, resolution: complaint.resolution }} staff={staff} /></div>
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-[26px] border border-white/10 bg-slate-900/80 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold"><MessageCircle className="h-5 w-5 text-cyan-300" />Customer-visible conversation</h2><div className="mt-4 space-y-3">{customerMessages.length ? customerMessages.map((message) => <Message key={message.id} author={message.author.name || message.author.email || "User"} message={message.message} date={message.createdAt} tone="customer" />) : <p className="text-sm text-slate-500">No customer-visible messages yet.</p>}</div>{notes.length ? <><h3 className="mt-6 border-t border-white/10 pt-5 text-sm font-bold uppercase tracking-wider text-amber-200">Internal notes</h3><div className="mt-3 space-y-3">{notes.map((message) => <Message key={message.id} author={message.author.name || message.author.email || "Staff"} message={message.message} date={message.createdAt} tone="internal" />)}</div></> : null}</section>
      <section className="rounded-[26px] border border-white/10 bg-slate-900/80 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold"><Clock3 className="h-5 w-5 text-cyan-300" />Immutable activity timeline</h2><div className="mt-5 space-y-4">{complaint.activities.map((activity) => <div key={activity.id} className="relative border-l border-cyan-400/25 pl-5"><span className="absolute -left-1 top-1 h-2 w-2 rounded-full bg-cyan-300" /><div className="text-sm font-semibold">{activity.summary}</div><div className="mt-1 text-xs text-slate-500">{activity.actorUser?.name || (activity.actorType === "SYSTEM" ? "System" : format(activity.actorType))} · {new Date(activity.createdAt).toLocaleString("en-KE")}</div></div>)}</div></section></div>
  </div>;
}

function Data({ label, value }: { label: string; value: string }) { return <div className="grid grid-cols-[120px_1fr] gap-3"><span className="text-slate-500">{label}</span><span className="break-words font-semibold text-slate-200">{value}</span></div>; }
function Message({ author, message, date, tone }: { author: string; message: string; date: Date; tone: "customer" | "internal" }) { return <div className={`rounded-2xl border p-4 text-sm ${tone === "internal" ? "border-amber-400/20 bg-amber-400/5" : "border-cyan-400/15 bg-cyan-400/5"}`}><div className="font-bold">{author}</div><p className="mt-1 whitespace-pre-wrap text-slate-300">{message}</p><div className="mt-2 text-xs text-slate-500">{new Date(date).toLocaleString("en-KE")}</div></div>; }
