import Link from "next/link";
import { redirect } from "next/navigation";
import { AlertTriangle, Clock3, Paperclip, Search } from "lucide-react";
import { auth } from "@/lib/auth";
import { complaintDashboardCounts, complaintStaffAccess, listAdminComplaints, COMPLAINT_PRIORITIES, COMPLAINT_STATUSES } from "@/lib/complaints";

export const dynamic = "force-dynamic";
const format = (value: string) => value.replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export default async function AdminComplaintsPage({ searchParams }: { searchParams: Promise<{ status?: string; priority?: string; query?: string }> }) {
  const session = await auth(); const user = session?.user as { role?: string; attendantCategory?: string } | undefined; if (!session) redirect("/admin/login"); if (!complaintStaffAccess(user || {})) redirect("/not-authorized");
  const filters = await searchParams; const [complaints, counts] = await Promise.all([listAdminComplaints(filters), complaintDashboardCounts()]);
  const openCount = COMPLAINT_STATUSES.filter((status) => !["RESOLVED", "CLOSED"].includes(status)).reduce((sum, status) => sum + (counts[status] || 0), 0);
  return <div className="space-y-6"><section className="overflow-hidden rounded-[30px] border border-white/10 bg-[radial-gradient(circle_at_85%_0%,rgba(34,211,238,.15),transparent_32%),linear-gradient(135deg,#111827,#020617)] p-6 sm:p-8">
    <div className="flex flex-wrap items-end justify-between gap-5"><div><div className="text-xs font-bold uppercase tracking-[.28em] text-cyan-300">Customer care operations</div><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Complaints & Issues</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Triage customer reports, coordinate technical and warranty work, record communication, and preserve a complete case history.</p></div><div className="rounded-2xl border border-cyan-400/20 bg-cyan-400/10 px-5 py-4"><div className="text-xs uppercase tracking-widest text-cyan-200">Open queue</div><div className="mt-1 text-3xl font-semibold text-white">{openCount}</div></div></div>
    <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{["NEW", "UNDER_REVIEW", "TECHNICAL_REVIEW", "WAITING_FOR_CUSTOMER", "RESOLVED"].map((status) => <Link key={status} href={`/admin/complaints?status=${status}`} className="rounded-2xl border border-white/10 bg-white/[.04] p-4 transition hover:border-cyan-400/30"><div className="text-xs uppercase tracking-wider text-slate-400">{format(status)}</div><div className="mt-2 text-2xl font-semibold">{counts[status] || 0}</div></Link>)}</div>
  </section>
  <section className="rounded-[28px] border border-white/10 bg-slate-900/75 p-5 sm:p-6"><form className="grid gap-3 lg:grid-cols-[1fr_220px_180px_auto]"><label className="relative"><Search className="absolute left-4 top-3.5 h-4 w-4 text-slate-500" /><input name="query" defaultValue={filters.query} placeholder="Search reference, customer, phone or title" className="w-full rounded-2xl border border-white/10 bg-slate-950 py-3 pl-11 pr-4 outline-none focus:border-cyan-400/40" /></label><select name="status" defaultValue={filters.status || ""} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">All statuses</option>{COMPLAINT_STATUSES.map((status) => <option value={status} key={status}>{format(status)}</option>)}</select><select name="priority" defaultValue={filters.priority || ""} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3"><option value="">All priorities</option>{COMPLAINT_PRIORITIES.map((priority) => <option value={priority} key={priority}>{format(priority)}</option>)}</select><button className="rounded-2xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Apply filters</button></form></section>
  <section className="grid gap-4">{complaints.length ? complaints.map((item) => <article key={item.id} className="grid gap-5 rounded-[26px] border border-white/10 bg-slate-900/75 p-5 lg:grid-cols-[1.2fr_.8fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-widest text-cyan-300">{item.reference}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wider ${item.priority === "URGENT" || item.priority === "HIGH" ? "bg-rose-500/15 text-rose-200" : "bg-white/5 text-slate-300"}`}>{item.priority}</span></div><h2 className="mt-2 text-xl font-semibold">{item.title}</h2><div className="mt-2 text-sm text-slate-400">{item.customer.name || "Customer"} · {item.customer.phone || item.customer.email || "No contact"}</div></div><div className="grid grid-cols-2 gap-3 text-sm"><div><div className="text-xs uppercase tracking-wider text-slate-500">Status</div><div className="mt-1 font-semibold text-amber-200">{format(item.status)}</div></div><div><div className="text-xs uppercase tracking-wider text-slate-500">Owner</div><div className="mt-1 font-semibold">{item.assignedTo?.name || "Unassigned"}</div></div><div className="flex items-center gap-1 text-slate-400"><Clock3 className="h-4 w-4" />{new Date(item.createdAt).toLocaleDateString("en-KE")}</div><div className="flex items-center gap-1 text-slate-400"><Paperclip className="h-4 w-4" />{item._count.attachments} evidence</div></div><Link href={`/admin/complaints/${item.reference}`} className="rounded-2xl border border-cyan-400/30 bg-cyan-400/10 px-5 py-3 text-center text-sm font-bold text-cyan-100">Open case</Link></article>) : <div className="rounded-[26px] border border-dashed border-white/15 p-12 text-center text-slate-400"><AlertTriangle className="mx-auto h-8 w-8" /><p className="mt-3">No complaints match the current filters.</p></div>}</section></div>;
}
