name: "Cron: Recompute Catalog Counters (hourly)"

on:
  schedule:
    - cron: "0 * * * *"  # every hour, at minute 0
  workflow_dispatch: {}

jobs:
  hit-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Recompute all catalog counters
        env:
          CRON_URL: ${{ secrets.CRON_RECOMPUTE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$CRON_URL" ]; then
            echo "CRON_RECOMPUTE_URL secret is not set" >&2
            exit 1
          fi
          if [ -z "$CRON_SECRET" ]; then
            echo "CRON_SECRET secret is not set" >&2
            exit 1
          fi
          echo "POST $CRON_URL"
          # Add all=true to be explicit; include a short timeout and retry on transient failures
          ATTEMPTS=0
          until [ $ATTEMPTS -ge 3 ]
          do
            ATTEMPTS=$((ATTEMPTS+1))
            set +e
            HTTP_CODE=$(curl -sS -X POST -H "x-cron-secret: $CRON_SECRET" -o response.json -w "%{http_code}" --max-time 45 "$CRON_URL")
            RC=$?
            set -e
            echo "HTTP: $HTTP_CODE (attempt $ATTEMPTS)"
            if [ "$RC" -eq 0 ] && [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
              cat response.json
              exit 0
            fi
            sleep 5
          done
          echo "Failed after $ATTEMPTS attempts:" >&2
          cat response.json || true
          exit 1
