name: "ARCHIVED: Prisma Deploy (use Primary pipeline)"

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Archived workflow. Use 'Primary: Migrate and Deploy to Vercel'."
        required: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Install Prisma
        run: npm install prisma --no-save
      - name: Archive notice
        run: |
          echo "This workflow is archived. Use 'Primary: Migrate and Deploy to Vercel'."
