name: Run set-admin (manual)

on:
  workflow_dispatch: {}

jobs:
  set-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma generate

      - name: Run set-admin script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node scripts/set-admin.js
