name: "ARCHIVED: Vercel Deploy (use prisma-and-vercel)"

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Archived workflow. Use 'Primary: Migrate and Deploy to Vercel' instead."
        required: false

jobs:
  vercel-deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Archive notice
        run: |
          echo "This workflow is archived. Use 'Primary: Migrate and Deploy to Vercel'."
