ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "showInShop" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopCategory" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopShortDescription" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopWarranty" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopSpecs" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopImageUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopBrand" TEXT;
