ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "showInShop" BOOLEAN;
UPDATE "Product" SET "showInShop" = FALSE WHERE "showInShop" IS NULL;
ALTER TABLE "Product" ALTER COLUMN "showInShop" SET DEFAULT FALSE;
ALTER TABLE "Product" ALTER COLUMN "showInShop" SET NOT NULL;

ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopCategory" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopShortDescription" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopWarranty" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopSpecs" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopImageUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shopBrand" TEXT;
